# Generated by Django 6.1 on 2026-09-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olcha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='swiper2',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='swiper2',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
